### ISSUE TITLE
NoMethodError is raised when attempting to join when not logged in

### ISSUE THREAD

**Issue by rjdellecese** [Firechess/firechess#45]
![nomethoderror](https://cloud.githubusercontent.com/assets/13547385/14583682/03f11720-03f7-11e6-9669-b57de9f52f50.jpg)

**Comment by lasley** [comment]
Closed with no explanation? Bad juju!

**Comment by rjdellecese** [comment]
The maintainers were unresponsive: looks like this project has been abandoned :stuck_out_tongue:
